### ISSUE TITLE
Arduino library manager has version 1.1.0 and links to this github but I can't find that version.

### ISSUE THREAD

**Issue by nophead** [akkoyun/RV3028#12]
As the title says but also the example included with it doesn't compile because it doesn't have `RV3028 RTC;` to define the object.

**Comment by akkoyun** [comment]
Hi friend. 
did you try the GitHub version (download and add to Arduino ide)?

**Comment by nophead** [comment]
No because it looked like an older version number but perhaps not. The version from the library manager only has RV3028.h. The version here has Registers.h and Definitions.h.

**Comment by nophead** [comment]
I discovered that version 1.1.0 in the Library manager is actually your 01.04.00 release here.  The library manager also offers 4 older versions and they seem to have the same version numbers as your four older releases, so just the last release has the wrong version number. 

You seem to have done a lot of updates and bug fixes since then so I will try installing your your latest code from the zip.

**Comment by nophead** [comment]
I have the clock connected to an RPI PICO W. With the last release the constructor locked up. With your latest code I am pleased to report it works. I also had to update your I2C_Functions library to get it to compile of course. Perhaps you might consider a new release of both.
